config/routes.rb
Rails.application.routes.draw do
  get 'api_requests/connection'
  get 'posts/index'
  post 'posts/create' 

  get 'categories/index'
  post 'categories/create'
  get 'categories/new'
  post 'categories/store'
  get 'categories/:id/edit', to: 'categories#edit', as: 'categories_edit'
  put 'categories/update/:id', to: 'categories#update', as: 'categories_update'
  put 'categories/update_form/:id', to: 'categories#update_form', as: 'categories_update_form'
  get 'categories/search_result'
  get 'categories/select'

  get 'articles/index'
  post 'articles/create'
  
  get 'api/request', to: 'api_requests#connection'

  get 'reserves/new' # 入力画面
  post 'reserves/confirm' # 確認画面
  post 'reserves/back' # 確認画面から「入力画面に戻る」をクリックしたとき
  post 'reserves/complete' # 完了画面
  
  get 'reserves/:id/edit', to: 'reserves#edit' , as: 'reserves_edit'
  post 'reserves/:id/edit_confirm', to: 'reserves#edit_confirm' , as: 'reserves_edit_confirm'
  put 'reserves/update/:id', to: 'reserves#update' , as: 'reserves_update'
  
  resources 'blogs' do
    collection do
      post 'confirm'
    end
    member do
      patch 'edit_confirm'
    end
  end


end

app/models/api_request.rb
class ApiRequest
    
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/models/category_article.rb
class CategoryArticle
  include ActiveModel::Model
    
  attr_accessor :name, :title, :body, :category_id

  def save
    category = Category.create(name: name)
    Article.create(title: title, body: body, category_id: category.id)
  end

  def update_form(category_find_params)
    
  end

  def search(search_name)
    Category.where("name LIKE ?", "%#{search_name}%")
  end
  
  def articles_category_search(search)
    # Category.eager_load(:articles).where(articles: {title: search})
    Category.eager_load(:articles).where("articles.title = ?", search)
  end
  
end

app/models/post.rb
class Post < ApplicationRecord
  attr_accessor :title
end

app/models/reserve.rb
class Reserve < ApplicationRecord
end

app/controllers/api_requests_controller.rb
class ApiRequestsController < ApplicationController 
    require 'net/http'
    require 'uri'
    require 'json'
    require 'csv'

    def connection
      url = URI.parse('http://localhost:3000/users') 
      req = Net::HTTP::Get.new(url.path)
      res = Net::HTTP.start(url.host, url.port) { |http| http.request(req) }
      @lists = JSON.parse(res.body)
      puts @lists["users"]
      @users = @lists["users"]
      
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_index_path
    else
      render articles_index_path
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :category_id)
  end
end

app/controllers/categories_controller.rb
require 'csv'

class CategoriesController < ApplicationController
  def index
    @category = Category.new
    
    p @articles
    if params[:category_search].present?
      category_search
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_index_path
    else
      render categories_index_path
    end
  end

  def new
    @category_article = CategoryArticle.new
  end
  
  # CategoriesテーブルとArticlesテーブルの複数テーブル登録(フォームオブジェクト)
  def store
    @category_article = CategoryArticle.new(category_article_params)
    if @category_article.save
      p @category_article
      redirect_to categories_index_path
    else
      render categories_new_path
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update!(category_params)
      redirect_to categories_search_result_path
    else
      render categories_edit_path
    end
  end

  def update_form
    @category = Category.find(params[:id])
    @category_article = CategoryArticle.new(@category, category_article_params)
    if @category_article.update_form(@category)
      redirect_to categories_search_result_path
    else
      render categories_edit_path
    end
  end
  
  def search_result
    if params[:search_name].present?
      category_article = CategoryArticle.new
      @categories = category_article.search(params[:search_name])
    end
    if params[:articles_title].present?
      category_article = CategoryArticle.new
      @articles_category = category_article.articles_category_search(params[:articles_title])
    end
  end

  def select
    @categories = Category.select(:name).distinct
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def category_search
    # @categories = Category.where("name LIKE ?", "%#{params[:category_search]}%")
    @articles = Article.joins(:category).where(categories: {id: params[:category_search]})
  end

  def category_article_params
    params.require(:category_article).permit(:name, :title, :body, :category_id)
  end

  def category_article_update_params
    params.permit(:name, :title, :body, :category_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @post = Post.new

    # 検索用
    if params[:search].present? 
      @posts = Post.where("title LIKE ?", "%#{params[:search]}%")
    end
    if params[:date_search].present?
      @posts = Post.where("contract = ?", params[:date_search])
    end
    p @posts
  end

  def create
    @post = Post.new(posts_params)
    if @post.save
      redirect_to posts_index_path
    else
      render posts_index_path
    end
  end

  private
  def posts_params
    params.require(:post).permit(:title, :contract)
  end
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController

    before_action :permit_params, except: :new
  
    def new
      @reserve = Reserve.new
    end
  
    def back
      @reserve = Reserve.new(@attr)
      render :new
    end
  
    def confirm
      @reserve = Reserve.new(@attr)
      if @reserve.invalid?
        render :new
      end
    end
  
    def complete
      Reserve.create!(@attr)
    end

    def edit
      @reserve = Reserve.find(params[:id])
    end

    def edit_confirm
      @reserve = Reserve.find(params[:id])
      
    end

    def update

    end

  
    private
  
    def permit_params
      @attr = params.require('reserve').permit(:id, :reserce_date, :name, :note)
    end
  
end

app/helpers/api_requests_helper.rb
module ApiRequestsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/views/api_requests/connection.html.erb
<h1>ApiRequests#connection</h1>
<p>Find me in app/views/api_requests/connection.html.erb</p>
<% @users.each do |user| %>
  <%= user["id"] %>
<% end %>

app/views/articles/index.html.erb
<h1>article#index</h1>
<%= form_with model: @article, url: articles_create_path, method: :post, local: true do |f| %>
<div class="form-group p-2">
  <%= f.text_field :title ,class: "form-control mb-2" %>
  <%= f.text_area :body ,class: "form-control mb-2" %>
  <%= f.select :category_id, {'スポーツ':1, '芸能': 2}, { include_blank: '選択してください'} ,class: "form-control mb-2" %>
  <%= f.submit '登録' ,class: "btn btn-primary" %>
</div>

<div>
  <%= link_to "カテゴリー" , categories_index_path %>
</div>
<% end %>

app/views/categories/edit.html.erb
<h1>Category#edit</h1>

<div>
  <%= @category.name %>
</div>

<div>
  <%= form_with model: @category, url: categories_update_path(@category.id) ,method: :put, local: true do |f| %>
    <%= f.text_field :name %>
    <%= f.submit '更新' %>
  <% end %>
</div>

<p class="mt-2">フォームオブジェクトで更新</p>
<div>
  <%= form_with model: @category_article, url: categories_update_form_path(@category.id), method: :put, local: true do |f| %>
    <%= f.text_field :name %>
    <%= f.text_field :title %>
    <%= f.text_area :body %>
    <%= f.submit '更新'%>
  <% end %>
</div>

app/views/categories/index.html.erb
<h1>category#index</h1>

<%= form_with  url: categories_index_path ,method: :get, local: true do |f| %>
<div class="form-group p-2">
  <%= f.text_field :category_search , class: "form-control mb-2" ,placeholder: "アーティクルとカテゴリーのinnerjoin検索、category_idとcategory.idで結合"%>
  <%= f.submit '検索' ,class: "btn btn-primary" %>
</div>
<% end %>

<h1>Search Result</h1>
<%# if @categories.present?%>
  <%# @categories.each do |category| %>
    <%#= category.name %>
  <%# end %>
<%# end %>
<% if @articles.present? %>
  <% @articles.each do |article| %>
    <%= article.title %>
  <% end%>
<% end %>

<div class="error-message">
  <p class="error-message-text"></p>
</div>

<%= form_with model: @category, url: categories_create_path, method: :post, local: true do |f| %>
<div class="form-group p-2">
  <%= f.text_field :name, class: "form-control mb-2"%>
  <%= f.submit "登録", class:"btn btn-primary" ,id: "btn_submit"%>
</div>

<div>
  <%= link_to "アーティクル" , articles_index_path %>
</div>
<% end %>

app/views/categories/new.html.erb
<h1>new</h1>

<%= form_with model: @category_article ,url: categories_store_path ,method: :post, local: true do |f|%>
  <div class="form-group">
    <%= f.text_field :name %>
    <%= f.text_field :title %>
    <%= f.text_area :body %>
    <%= f.submit '投稿' %>
  </div>


<% end %>

app/views/categories/search_result.html.erb
<h1>SearchResult</h1>

<%= form_with url: categories_search_result_path, method: :get, local: true do |f| %>
  <p>ただのカテゴリーネームのあいまい検索</p>
  <%= f.text_field :search_name %>
  <%= f.submit '検索' %>
<% end %>

<div class="result">

<% if @categories.present? %>
  <ul>
    <% @categories.each do |category| %>
    <li>
      <%= category.name %>
    </li>
    <% end %>
  </ul>
<% end %>
</div>

<%= form_with url: categories_search_result_path, method: :get, local: true do |f| %>
  <p>Articleのタイトルから完全一致カテゴリー検索</p>
  <%= f.text_field :articles_title %>
  <%= f.submit '検索' %>
<% end %>

<div class="result">
  <% if @articles_category.present? %>
    <ul>
      <% @articles_category.each do |category| %>
      <li>
        <%= category.name %>
      </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/categories/select.html.erb
<h1>Category#Select</h1>
<%= form_with model: @categories, url: categories_create_path, method: :post, local: true do |f| %>
  <%= f.collection_select(:name, @categories, :id, :name) %>
  <%= f.submit '登録' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleCsvApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_search.html.erb
<h2 class="p-2">SearchResults</h2>

<% if params[:search].present? || params[:date_search].present? %>
  <ul style="list-style:none">
    <% @posts.each do |post| %>
      <% unless post.title == nil %>
        <li>
          <%= post.title %>
          <%= post.contract %>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/posts/index.html.erb
<h1 class="title p-2">Posts#index</h1>
<%= form_with model: @post, url: posts_create_path ,method: :post, local: true, class: "p-2" do |f| %>
  <div class="form-group">
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.date_field :contract %>
  </div>
  <%= f.submit "登録", class: "btn btn-primary" %>
<% end %>

<div>
  <%= form_with url: posts_index_path, method: :get, local: true, class: "p-2" do |f| %>
   <div class="form-group">
      <%= f.text_field :search %>
   </div>
   <div class="form-group">
      <%= f.date_field :date_search %>
   </div>
    <%= f.submit "検索", class: "btn btn-primary" %>
  <% end %>
</div>

<div>
  <%= render 'posts/search' %>
</div>

app/views/reserves/complete.html.erb
<h1>予約フォーム</h1>

<ol class="nav">
	<li>1.入力</li>
	<li>2.確認</li>
	<li class="current">3.完了</li>
</ol>

<p>ご予約ありがとうございました。</p>

app/views/reserves/confirm.html.erb
<h1>予約フォーム</h1>

<ol class="nav">
	<li>1.入力</li>
	<li class="current">2.確認</li>
	<li>3.完了</li>
</ol>

<dl>
	<dt>希望日</dt>
	<dd><%= @reserve.reserce_date %></dd>
	<dt>名前</dt>
	<dd><%= @reserve.name %></dd>
	<dt>備考</dt>
	<dd><%= @reserve.note %></dd>
</dl>

<%= form_for @reserve, method: :post, url: reserves_back_path do |form| %>
	<%= form.hidden_field :reserce_date %>
	<%= form.hidden_field :name %>
	<%= form.hidden_field :note %>
	<%= form.submit '入力画面に戻る' %>
<% end %>

<%= form_for @reserve, method: :post, url: reserves_complete_path do |form| %>
	<%= form.hidden_field :reserce_date %>
	<%= form.hidden_field :name %>
	<%= form.hidden_field :note %>
	<%= form.submit '送信する' %>
<% end %>

app/views/reserves/new.html.erb
<h1>予約フォーム</h1>

<ol class="nav">
	<li class="current">1.入力</li>
	<li>2.確認</li>
	<li>3.完了</li>
</ol>

<%= form_for @reserve, method: :post, url: reserves_confirm_path do |form| %>
	<dl>
		<dt>希望日</dt>
		<dd><%= form.text_field :reserce_date %></dd>
		<dt>名前</dt>
		<dd><%= form.text_field :name %></dd>
		<dt>備考</dt>
		<dd><%= form.text_field :note %></dd>
	</dl>

	<%= form.submit '確認画面へ' %>
<% end %>